name: Deploy to iFastNet via Git Push

on:
  push:
    branches:
      - main  # Or whatever branch you want to deploy from

jobs:
  push-to-ifastnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so we can push correctly

      - name: Install SSH Key for iFastNet
        uses: shimataro/ssh-key-action@v2.7.0 # Using a specific version is good practice
        with:
          key: ${{ secrets.IFASTNET }}                # Updated secret name for private key
          passphrase: ${{ secrets.IFASTNET_PASS }}       # Updated secret name for passphrase
          known_hosts: ${{ secrets.IFASTNET_KNOWN_HOSTS }} # Using secret for known_hosts
          # name: id_ifastnet_action # Optional: name of the key file once created on the runner

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add iFastNet as a remote
        run: |
          # Remove remote if it already exists to avoid errors on re-runs
          git remote remove ifastnet || true
          git remote add ifastnet ssh://kreftus@kreft.us:27015/home/kreftus/gitcode

      - name: Push to iFastNet
        run: |
          git push ifastnet main --force
          # Using --force might be necessary if the histories can diverge
          # or if the iFastNet repo is non-bare and its HEAD needs to be overwritten.
          # Use with caution: ensures iFastNet repo matches the GitHub repo state.