name: Deploy to iFastNet via Git Push

on:
  push:
    branches:
      - main  # Or whatever branch you want to deploy from

jobs:
  push-to-ifastnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH Key for iFastNet
        uses: shimataro/ssh-key-action@v2 # Using shimataro/ssh-key-action
        with:
          key: ${{ secrets.IFASTNET_PASS }}
          name: id_ifastnet_action # Optional: name of the key file once created on the runner
          known_hosts: ${{ secrets.IFASTNET_KNOWN_HOSTS }} # Store your server's host key here as a secret
          passphrase: ${{ secrets.IFASTNET_PASS }} # Use the passphrase secret

      # The ssh-keyscan step for known_hosts might still be useful if you don't want to manage
      # the full known_hosts entry as a secret, but shimataro/ssh-key-action can use a direct entry.
      # If you don't use the 'known_hosts' input in the action above, keep a step like this:
      # - name: Add iFastNet to known_hosts (alternative)
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -p 27015 kreft.us >> ~/.ssh/known_hosts

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add iFastNet as a remote
        run: |
          git remote add ifastnet ssh://kreftus@kreft.us:27015/home/kreftus/gitcode

      - name: Push to iFastNet
        run: |
          git push ifastnet main --force
