name: Deploy to iFastNet via Git Push

on:
  push:
    branches:
      - main

jobs:
  push-to-ifastnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.IFASTNET }} # Your passphrase-PROTECTED private key
        # This action will attempt to ssh-add the key.
        # For it to work with a passphrase, the key needs to be in a format ssh-add can handle,
        # and this action would need to somehow facilitate the passphrase provision.
        # If this step fails with "error in libcrypto", it means it couldn't decrypt the key.

      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.IFASTNET_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add iFastNet as a remote
        run: |
          git remote remove ifastnet || true
          git remote add ifastnet ssh://kreftus@kreft.us:27015/home/kreftus/gitcode

      - name: Push to iFastNet
        env:
          GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/home/runner/.ssh/known_hosts" # Ensure our known_hosts is used
        run: |
          git push ifastnet main --force
