- name: Setup SSH Agent and Add Key with Passphrase
        env:
          SSH_PRIVATE_KEY_CONTENT: ${{ secrets.IFASTNET }}      # Your passphrase-PROTECTED private key
          SSH_KEY_PASSPHRASE: ${{ secrets.IFASTNET_PASS }}   # The passphrase for your private key
        run: |
          echo "Starting ssh-agent..."
          eval "$(ssh-agent -s)" # Start the ssh-agent

          echo "Creating private key file..."
          mkdir -p ~/.ssh
          # Ensure this filename is used consistently
          echo "$SSH_PRIVATE_KEY_CONTENT" > ~/.ssh/ifastnet_action_key # Using ifastnet_action_key
          chmod 600 ~/.ssh/ifastnet_action_key # Set correct permissions

          echo "Adding key to ssh-agent with expect..."
          expect <<EOF
          set timeout 10
          # Corrected filename here:
          spawn ssh-add ~/.ssh/ifastnet_action_key 
          expect {
            # Corrected filename in the expect prompt pattern:
            "Enter passphrase for ~/.ssh/ifastnet_action_key:" { 
              send "$SSH_KEY_PASSPHRASE\r"
              exp_continue
            }
            eof {
              # If ssh-add exits successfully, this will be fine.
            }
            timeout {
              puts "Timeout waiting for passphrase prompt or eof"
              exit 1
            }
          }
          EOF

          echo "Verifying if key was added..."
          ssh-add -l # List keys in agent.
