name: Deploy to iFastNet via Git Push

on:
  push:
    branches:
      - main

jobs:
  push-to-ifastnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # REMOVE THE ENTIRE "Start SSH Agent" (webfactory/ssh-agent) STEP

      - name: Install SSH Key for iFastNet
        uses: shimataro/ssh-key-action@v2.7.0 # Or the latest v2.x.x version
        with:
          key: ${{ secrets.IFASTNET }}                # Your passphrase-PROTECTED private key
          passphrase: ${{ secrets.IFASTNET_PASS }}       # Your passphrase secret
          known_hosts: ${{ secrets.IFASTNET_KNOWN_HOSTS }} # Your known_hosts entry
        # DO NOT add a 'run:' block here for ssh-add or expect

      # The "Add iFastNet to known_hosts" step is also handled by the
      # 'known_hosts:' input in the shimataro/ssh-key-action above.
      # So, you can REMOVE the separate "Add iFastNet to known_hosts" step below
      # if secrets.IFASTNET_KNOWN_HOSTS is correctly populated.
      # If you prefer to keep ssh-keyscan as a fallback, ensure it doesn't conflict.
      # For robustness, relying on the secret is better.

      # - name: Add iFastNet to known_hosts # This step can likely be removed
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.IFASTNET_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add iFastNet as a remote
        run: |
          git remote remove ifastnet || true
          git remote add ifastnet ssh://kreftus@kreft.us:27015/home/kreftus/gitcode

      - name: Push to iFastNet
        run: |
          git push ifastnet main --force
